### ISSUE TITLE
Viewbuilder view constructor properties

### ISSUE THREAD

**Issue by emuell** [renoise/definitions#17]
Continuing discussion from https://github.com/renoise/definitions/pull/16#issuecomment-1961563618

> On a related note, I think write-only fields like `pressed` should be marked `private` (or `protected`) as they are not even write-only in the sense that you can't even write to them (only in the construction table which should be its own class anyway).
> 
> So for example after creating a button, you can't do
> 
> ```lua
> b = vb:button { text = "x" }
> b.pressed = function() end
> ```
> 
> but the language server will happily auto-complete a function for `b.pressed` right now, which will crash at runtime later.
> 
> If they were notated as
> 
> ```lua
> ---@field private pressed ...
> ```
> 
> the editor wouldn't offer the completion and it would warn you with "pressed is private and can't be accessed..." if you were trying to assign a function to it.

I think those should be removed from the class docs instead, and should only be present in new, not yet present viewbuilder constructor table properties. Only this way we can also get rid of the functions there too.

For example:
```lua
---General ViewBuilder View properties
---@class ViewProperties 
---@field id string?
---@field width (integer|string)?
---@field height (integer|string)?
---@field visible boolean?
---@field tooltip string?

---Rack ViewBuilder View properties
---@class RackProperties : ViewProperties
---@field margin integer?
---@field spacing integer?
---@field style RackStyle?
---@field uniform boolean?

---{ Rack Properties and/or child views }
---@param properties RackProperties
---@return renoise.Views.Rack rack
function renoise.ViewBuilder:column(properties) end
``` 

Not sure how to express the ability to add child views as well:
```lua
renoise.ViewBuilder:column({
  margin = 20,
  renoise.ViewBuilder:text({ text = "Bla" })
})
```

**Comment by emuell** [comment]
Already started collecting all viewbuilder properties from the C++ code now:

```md
ViewProperties
  { "id", "width", "height", "visible", "tooltip" }

ControlProperties
  { "active", "midi_mapping" }

RackViewProperties
  { "margin", "spacing", "style", "uniform" }

AlignmentRackViewProperties
  { "margin", "spacing", "mode" }

TextViewProperties
  { "text", "font", "style", "align" }

MultilineTextViewProperties
  { "text", "paragraphs", "font", "style" }

TextFieldProperties
  { "bind", "active", "value", "notifier", "text", "align", "edit_mode" }

MultilineTextFieldProperties
  { "bind", "active", "value", "notifier", "text", "paragraphs", "font", "style", "edit_mode" }

ButtonProperties
  { "text", "bitmap", "color", "notifier", "pressed", "released" }

BitmapViewProperties
  { "mode", "bitmap", "notifier" }

CheckBoxProperties
  { "bind", "value", "notifier" }

ButtonSwitchProperties
  { "bind", "value", "notifier", "items" }

PopUpMenuProperties
  { "bind", "value", "notifier", "items" }

ChooserProperties
  { "bind", "value", "notifier", "items" }

ValueBoxProperties
  { "bind", "value", "notifier", "min", "max", "steps", "tostring", "tonumber" }

ValueViewProperties
  { "bind", "value", "notifier", "align", "font", "tostring" }

ValueFieldProperties
  { "bind", "value", "notifier", "min", "max", "align", "tostring", "tonumber" }

SliderProperties
  { "bind", "value", "notifier", "min", "max", "steps", "default" }

MiniSliderProperties
  { "bind", "value", "notifier", "min", "max", "default" }

RotaryEncoderProperties
  { "bind", "value", "notifier", "min", "max", "default" }

XYPadProperties
  { "bind", "value", "snapback", "notifier", "min", "max" }

#### child views allowed:

row, column
  { ViewProperties, RackViewProperties }
vertical_aligner, horizontal_aligner
  { ViewProperties, AlignmentRackViewProperties }
space
  { ViewProperties }

#### no child views allowed:

text
  { ViewProperties, TextViewProperties }

multiline_text
  { ViewProperties, MultilineTextViewProperties }

textfield
  { ViewProperties, TextFieldProperties }

multiline_textfield
  { ViewProperties, MultilineTextFieldProperties }

value
  { ViewProperties, ValueViewProperties }

bitmap
  { ViewProperties, ControlProperties, BitmapViewProperties }

button
  { ViewProperties, ControlProperties, ButtonProperties }

checkbox
    { ViewProperties, ControlProperties, CheckBoxProperties }

switch
    { ViewProperties, ControlProperties, ButtonSwitchProperties }

popup
    { ViewProperties, ControlProperties, PopUpMenuProperties }

chooser
    { ViewProperties, ControlProperties, ChooserProperties }

valuebox
    { ViewProperties, ControlProperties, ValueBoxProperties }

valuefield
    { ViewProperties, ControlProperties, ValueFieldProperties }

slider
    { ViewProperties, ControlProperties, SliderProperties }

minislider
    { ViewProperties, ControlProperties, MiniSliderProperties }

rotary
    { ViewProperties, ControlProperties, RotaryEncoderProperties }

xypad
    { ViewProperties, ControlProperties, XYPadProperties }
```

**Comment by unlessgames** [comment]
Yeah, that would be even better and it's a good step towards it to have the props collected in one place here!

Maybe I'm missing something but I don't think we can express the optional child views through the type system in luals. The best that could be done is to write comments with examples for the properties or view constructors or a link to a central explanation.

Personally this was one of the most confusing detail to me getting into tools as well, like it's a struct but it's also a list, haven't seen this before in any other place, while I admit it's nice to use once you get it, maybe it would be cleaner to deprecate or extend this API and use something like f(props, ...views) instead which could be annotated as

```lua 
---@param props XProperties
---@param ... View
function ViewBuilder:x(props, ...) end
```
see *Variable Number of Parameters* in the docs https://luals.github.io/wiki/annotations/#param

**Comment by emuell** [comment]
> Maybe I'm missing something but I don't think we can express the optional child views through the type system in luals. The best that could be done is to write comments with examples for the properties or view constructors or a link to a central explanation.

Yes, as long as this doesn't get picked up as a diagnostic error, this should be fine. Some examples in the vb:column, vb:row docs should clear things up then.

> Personally this was one of the most confusing detail to me getting into tools as well, like it's a struct but it's also a list, haven't seen this before in any other place, while I admit it's nice to use once you get it, maybe it would be cleaner to deprecate or extend this API and use something like f(props, ...views) instead which could be annotated as

Indeed. Or by using a new "childs" *or "views" or "subviews") property:

```lua
vb:row{
  margin = 20, 
  views = {
    vb:text{...}, 
    vb:button{...}
  }
}
```

**Comment by emuell** [comment]
For completeness here's the list of valid properties outside of the viewbuilder for all views (again ripped of the C++ code):

Example:
```lua
local my_button = vb:button()
my_button.text = "Some Text"
```

```
renoise.Views.View
  visible
  width
  height
  tooltip

renoise.Views.Control
  active
  midi_mapping

renoise.Views.Rack
  margin
  spacing
  style
  uniform

renoise.Views.Aligner
  margin
  spacing
  mode

renoise.Views.Text
  text
  font
  style
  align

renoise.Views.MultiLineText
  text
  paragraphs
  font
  style

renoise.Views.TextField
  active
  value
  text
  align
  edit_mode

renoise.Views.MultiLineTextField
  active
  text
  paragraphs
  font
  style
  edit_mode

renoise.Views.Button
  text
  bitmap
  color

renoise.Views.Bitmap
  mode
  bitmap

renoise.Views.CheckBox
  value

renoise.Views.Switch
  items
  value

renoise.Views.Popup
  items
  value

renoise.Views.Chooser
  items
  value

renoise.Views.ValueBox
  min
  max
  steps
  value

renoise.Views.Value
  value
  align
  font

renoise.Views.ValueField
  min
  max
  value
  align

renoise.Views.Slider
  min
  max
  steps
  default
  value

renoise.Views.MiniSlider
  min
  max
  default
  value

renoise.Views.Rotary
  min
  max
  default
  value

renoise.Views.XYPad
  min
  max
  value
  snapback
```

**Comment by emuell** [comment]
Fixed in https://github.com/renoise/definitions/pull/19
