### ISSUE TITLE
New constants for the API

### ISSUE THREAD

**Issue by unlessgames** [renoise/definitions#23]
Might be nice to have constants accessible through the API for some "magic numbers" that are currently only defined as a `Range: (x - y)` comment following fields.

IMO, these would be rather commonly accessed

* Transport.MIN_BPM
* Transport.MAX_BPM
* Transport.MAX_LPB
* Transport.MAX_TPL

But things like...

* SampleModulationSet.MAX_PITCH_RANGE
* SampleEnvelopeModulationDevice.MIN_ENVELOPE_LENGTH
* SampleEnvelopeModulationDevice.MAX_ENVELOPE_LENGTH

..might also be nice.

**Comment by emuell** [comment]
This would be nice indeed, but let's keep those discussions in the [Renoise forum](https://forum.renoise.com/c/renoise-tool-development/19) and discuss plain type definition issues, bugs here only.
